-- AlterTable
ALTER TABLE "Member" ADD COLUMN     "fresh_until" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "fresh_until" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
