on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm install
      - run: npm run check
      - run: npm run lint
